// 16.eProductPage/src/lib/components/aside.svelte
<script lang="ts">
    export let asideIsOpen = false;
    export let items: string[] = [];
</script>

<aside class={`fixed inset-0 w-screen h-screen bg-black/75 transition-opacity duration-300 z-20 ${
        asideIsOpen ? 'pointer-events-auto' : 'opacity-0 pointer-events-none' }`}>
    <div class={`absolute top-0 left-0 h-full w-[15rem] bg-white p-6 transform transition-transform 
        duration-300 ease-in-out z-30 ${asideIsOpen ? 'translate-x-0' : '-translate-x-full' }`}>
        <button class="mb-8 cursor-pointer" on:click={() => (asideIsOpen = false)}>
            <img src="/icons/close.svg" alt="close" />
        </button>
        {#each items as item}
            <p class="font-bold text-lg mt-4 cursor-pointer text-very-dark-blue">{item}</p>
        {/each}
    </div>
</aside>

// 15.newsHomePage/components/Aside.vue
<script setup lang="ts">
  import { defineModel, defineProps, ref, watch, nextTick } from 'vue'
  import 'animate.css'
  const controler = defineModel<boolean>('controler')
  const { items } = defineProps<{ items: string[] }>()
  const showBackdrop = ref(controler.value)
  const showSidebar = ref(controler.value)
  const sidebarRef = ref<HTMLElement | null>(null)
  watch(controler, async (visible) => {
    const el = sidebarRef.value!
    if (visible) {
      showSidebar.value = true
      showBackdrop.value = true
      await nextTick()
      el.classList.replace('animate__slideOutRight', 'animate__slideInRight')
    } else {
      el.classList.replace('animate__slideInRight', 'animate__slideOutRight')
      el.addEventListener('animationend',() => {
          showSidebar.value = false
          showBackdrop.value = false
        },
        { once: true }
      )
    }
  },
  { flush: 'post' }
)
</script>

<template>
  <div v-if="showBackdrop" @click="controler = false" class="fixed inset-0 bg-black bg-opacity-50 z-40"></div>
  <aside v-if="showSidebar" ref="sidebarRef" class=" fixed inset-y-0 right-0 w-64 bg-white z-50 overflow-y-auto animate__animated animate__slideInRight">
    <button @click="controler = false" class="absolute top-5 right-5 cursor-pointer"><img src="/images/icon-menu-close.svg" alt="close menu" class="w-6 h-6" /></button>
    <ul class="mt-32">
      <li v-for="(item, idx) in items" :key="idx" class="navItem">
        <button class="w-full text-left px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500">
          <p>{{item}}</p>
        </button>
      </li>
    </ul>
  </aside>
</template>
